package com.thirtydegreesray.openhub.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTH_USER".
*/
public class AuthUserDao extends AbstractDao<AuthUser, String> {

    public static final String TABLENAME = "AUTH_USER";

    /**
     * Properties of entity AuthUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property AccessToken = new Property(0, String.class, "accessToken", true, "ACCESS_TOKEN");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property AuthTime = new Property(2, java.util.Date.class, "authTime", false, "AUTH_TIME");
        public final static Property ExpireIn = new Property(3, int.class, "expireIn", false, "EXPIRE_IN");
        public final static Property Scope = new Property(4, String.class, "scope", false, "SCOPE");
        public final static Property Selected = new Property(5, boolean.class, "selected", false, "SELECTED");
    };


    public AuthUserDao(DaoConfig config) {
        super(config);
    }
    
    public AuthUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTH_USER\" (" + //
                "\"ACCESS_TOKEN\" TEXT PRIMARY KEY NOT NULL ," + // 0: accessToken
                "\"USER_ID\" TEXT," + // 1: userId
                "\"AUTH_TIME\" INTEGER NOT NULL ," + // 2: authTime
                "\"EXPIRE_IN\" INTEGER NOT NULL ," + // 3: expireIn
                "\"SCOPE\" TEXT NOT NULL ," + // 4: scope
                "\"SELECTED\" INTEGER NOT NULL );"); // 5: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTH_USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthUser entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getAccessToken());
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
        stmt.bindLong(3, entity.getAuthTime().getTime());
        stmt.bindLong(4, entity.getExpireIn());
        stmt.bindString(5, entity.getScope());
        stmt.bindLong(6, entity.getSelected() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthUser entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getAccessToken());
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
        stmt.bindLong(3, entity.getAuthTime().getTime());
        stmt.bindLong(4, entity.getExpireIn());
        stmt.bindString(5, entity.getScope());
        stmt.bindLong(6, entity.getSelected() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public AuthUser readEntity(Cursor cursor, int offset) {
        AuthUser entity = new AuthUser( //
            cursor.getString(offset + 0), // accessToken
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            new java.util.Date(cursor.getLong(offset + 2)), // authTime
            cursor.getInt(offset + 3), // expireIn
            cursor.getString(offset + 4), // scope
            cursor.getShort(offset + 5) != 0 // selected
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthUser entity, int offset) {
        entity.setAccessToken(cursor.getString(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setExpireIn(cursor.getInt(offset + 3));
        entity.setScope(cursor.getString(offset + 4));
        entity.setSelected(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(AuthUser entity, long rowId) {
        return entity.getAccessToken();
    }
    
    @Override
    public String getKey(AuthUser entity) {
        if(entity != null) {
            return entity.getAccessToken();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
