package com.thirtydegreesray.openhub.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUTH_USER".
 */
@Entity
public class AuthUser {

    @Id
    @NotNull
    private String accessToken;
    private String userId;

    @NotNull
    private java.util.Date authTime;
    private int expireIn;

    @NotNull
    private String scope;
    private boolean selected;

    @Generated
    public AuthUser() {
    }

    public AuthUser(String accessToken) {
        this.accessToken = accessToken;
    }

    @Generated
    public AuthUser(String accessToken, String userId, java.util.Date authTime, int expireIn, String scope, boolean selected) {
        this.accessToken = accessToken;
        this.userId = userId;
        this.authTime = authTime;
        this.expireIn = expireIn;
        this.scope = scope;
        this.selected = selected;
    }

    @NotNull
    public String getAccessToken() {
        return accessToken;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccessToken(@NotNull String accessToken) {
        this.accessToken = accessToken;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @NotNull
    public java.util.Date getAuthTime() {
        return authTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthTime(@NotNull java.util.Date authTime) {
        this.authTime = authTime;
    }

    public int getExpireIn() {
        return expireIn;
    }

    public void setExpireIn(int expireIn) {
        this.expireIn = expireIn;
    }

    @NotNull
    public String getScope() {
        return scope;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScope(@NotNull String scope) {
        this.scope = scope;
    }

    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public boolean isExpired(){
        return authTime.getTime() + expireIn * 1000 < System.currentTimeMillis();
    }

}
