package com.thirtydegreesray.openhub.db;

import android.support.annotation.NonNull;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    @NonNull private final DaoConfig authUserDaoConfig;

    @NonNull private final AuthUserDao authUserDao;

    public DaoSession(Database db, IdentityScopeType type, @NonNull Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authUserDaoConfig = daoConfigMap.get(AuthUserDao.class).clone();
        authUserDaoConfig.initIdentityScope(type);

        authUserDao = new AuthUserDao(authUserDaoConfig, this);

        registerDao(AuthUser.class, authUserDao);
    }
    
    public void clear() {
        authUserDaoConfig.getIdentityScope().clear();
    }

    @NonNull
    public AuthUserDao getAuthUserDao() {
        return authUserDao;
    }

}
